services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: ai-chat-pdf-backend
    ports:
      - "8000:8000"
    environment:
      - ENVIRONMENT=production
    volumes:
      - backend_data:/app/database
      - backend_memories:/app/memories
      - backend_uploads:/app/updated
    networks:
      - ai-chat-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:8000/health')"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: ai-chat-pdf-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - ai-chat-network
    restart: unless-stopped

volumes:
  backend_data:
    driver: local
  backend_memories:
    driver: local
  backend_uploads:
    driver: local

networks:
  ai-chat-network:
    driver: bridge
